// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/getamis/service-broker/broker/pb/types.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Catalog struct {
	Services []*Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *Catalog) Reset()                    { *m = Catalog{} }
func (m *Catalog) String() string            { return proto.CompactTextString(m) }
func (*Catalog) ProtoMessage()               {}
func (*Catalog) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Catalog) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name            string                  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id              string                  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Description     string                  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Bindable        bool                    `protobuf:"varint,4,opt,name=bindable" json:"bindable,omitempty"`
	PlanUpdateable  bool                    `protobuf:"varint,5,opt,name=plan_updateable,json=planUpdateable" json:"plan_updateable,omitempty"`
	Tags            []string                `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	Requires        []string                `protobuf:"bytes,7,rep,name=requires" json:"requires,omitempty"`
	Metadata        *google_protobuf.Struct `protobuf:"bytes,8,opt,name=metadata" json:"metadata,omitempty"`
	Plans           []*Plan                 `protobuf:"bytes,9,rep,name=plans" json:"plans,omitempty"`
	DashboardClient *google_protobuf.Struct `protobuf:"bytes,10,opt,name=dashboard_client,json=dashboardClient" json:"dashboard_client,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Service) GetBindable() bool {
	if m != nil {
		return m.Bindable
	}
	return false
}

func (m *Service) GetPlanUpdateable() bool {
	if m != nil {
		return m.PlanUpdateable
	}
	return false
}

func (m *Service) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Service) GetRequires() []string {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *Service) GetMetadata() *google_protobuf.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Service) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func (m *Service) GetDashboardClient() *google_protobuf.Struct {
	if m != nil {
		return m.DashboardClient
	}
	return nil
}

type Plan struct {
	Name        string                  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id          string                  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Description string                  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Metadata    *google_protobuf.Struct `protobuf:"bytes,4,opt,name=metadata" json:"metadata,omitempty"`
	Free        bool                    `protobuf:"varint,5,opt,name=free" json:"free,omitempty"`
}

func (m *Plan) Reset()                    { *m = Plan{} }
func (m *Plan) String() string            { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()               {}
func (*Plan) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Plan) GetMetadata() *google_protobuf.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Plan) GetFree() bool {
	if m != nil {
		return m.Free
	}
	return false
}

type Instance struct {
	Id               string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DashboardUrl     string                  `protobuf:"bytes,2,opt,name=dashboard_url,json=dashboardUrl" json:"dashboard_url,omitempty"`
	InternalId       string                  `protobuf:"bytes,3,opt,name=internal_id,json=internalId" json:"internal_id,omitempty"`
	ServiceId        string                  `protobuf:"bytes,4,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	PlanId           string                  `protobuf:"bytes,5,opt,name=plan_id,json=planId" json:"plan_id,omitempty"`
	OrganizationGuid string                  `protobuf:"bytes,6,opt,name=organization_guid,json=organizationGuid" json:"organization_guid,omitempty"`
	SpaceGuid        string                  `protobuf:"bytes,7,opt,name=space_guid,json=spaceGuid" json:"space_guid,omitempty"`
	LastOperation    *LastOperation          `protobuf:"bytes,8,opt,name=last_operation,json=lastOperation" json:"last_operation,omitempty"`
	Parameters       *google_protobuf.Struct `protobuf:"bytes,9,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetDashboardUrl() string {
	if m != nil {
		return m.DashboardUrl
	}
	return ""
}

func (m *Instance) GetInternalId() string {
	if m != nil {
		return m.InternalId
	}
	return ""
}

func (m *Instance) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Instance) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *Instance) GetOrganizationGuid() string {
	if m != nil {
		return m.OrganizationGuid
	}
	return ""
}

func (m *Instance) GetSpaceGuid() string {
	if m != nil {
		return m.SpaceGuid
	}
	return ""
}

func (m *Instance) GetLastOperation() *LastOperation {
	if m != nil {
		return m.LastOperation
	}
	return nil
}

func (m *Instance) GetParameters() *google_protobuf.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Binding struct {
	Id                string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ServiceId         string `protobuf:"bytes,2,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	AppId             string `protobuf:"bytes,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	ServicePlanId     string `protobuf:"bytes,4,opt,name=service_plan_id,json=servicePlanId" json:"service_plan_id,omitempty"`
	PrivateKey        string `protobuf:"bytes,5,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	ServiceInstanceId string `protobuf:"bytes,6,opt,name=service_instance_id,json=serviceInstanceId" json:"service_instance_id,omitempty"`
}

func (m *Binding) Reset()                    { *m = Binding{} }
func (m *Binding) String() string            { return proto.CompactTextString(m) }
func (*Binding) ProtoMessage()               {}
func (*Binding) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Binding) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Binding) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Binding) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Binding) GetServicePlanId() string {
	if m != nil {
		return m.ServicePlanId
	}
	return ""
}

func (m *Binding) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *Binding) GetServiceInstanceId() string {
	if m != nil {
		return m.ServiceInstanceId
	}
	return ""
}

type ServiceBindingRequest struct {
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	BindingId string `protobuf:"bytes,2,opt,name=binding_id,json=bindingId" json:"binding_id,omitempty"`
}

func (m *ServiceBindingRequest) Reset()                    { *m = ServiceBindingRequest{} }
func (m *ServiceBindingRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceBindingRequest) ProtoMessage()               {}
func (*ServiceBindingRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ServiceBindingRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceBindingRequest) GetBindingId() string {
	if m != nil {
		return m.BindingId
	}
	return ""
}

type ServiceBindingResponse struct {
	Credentials *google_protobuf.Struct `protobuf:"bytes,1,opt,name=credentials" json:"credentials,omitempty"`
}

func (m *ServiceBindingResponse) Reset()                    { *m = ServiceBindingResponse{} }
func (m *ServiceBindingResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceBindingResponse) ProtoMessage()               {}
func (*ServiceBindingResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ServiceBindingResponse) GetCredentials() *google_protobuf.Struct {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type ServiceInstanceRequest struct {
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
}

func (m *ServiceInstanceRequest) Reset()                    { *m = ServiceInstanceRequest{} }
func (m *ServiceInstanceRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceInstanceRequest) ProtoMessage()               {}
func (*ServiceInstanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ServiceInstanceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type ServiceInstanceResponse struct {
	DashboardUrl  string         `protobuf:"bytes,1,opt,name=dashboard_url,json=dashboardUrl" json:"dashboard_url,omitempty"`
	LastOperation *LastOperation `protobuf:"bytes,2,opt,name=last_operation,json=lastOperation" json:"last_operation,omitempty"`
}

func (m *ServiceInstanceResponse) Reset()                    { *m = ServiceInstanceResponse{} }
func (m *ServiceInstanceResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceInstanceResponse) ProtoMessage()               {}
func (*ServiceInstanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ServiceInstanceResponse) GetDashboardUrl() string {
	if m != nil {
		return m.DashboardUrl
	}
	return ""
}

func (m *ServiceInstanceResponse) GetLastOperation() *LastOperation {
	if m != nil {
		return m.LastOperation
	}
	return nil
}

type Credential struct {
	PublicIp   string `protobuf:"bytes,1,opt,name=public_ip,json=publicIp" json:"public_ip,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
}

func (m *Credential) Reset()                    { *m = Credential{} }
func (m *Credential) String() string            { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()               {}
func (*Credential) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Credential) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *Credential) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credential) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type LastOperation struct {
	State                    string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Description              string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	AsyncPollIntervalSeconds int32  `protobuf:"varint,3,opt,name=async_poll_interval_seconds,json=asyncPollIntervalSeconds" json:"async_poll_interval_seconds,omitempty"`
}

func (m *LastOperation) Reset()                    { *m = LastOperation{} }
func (m *LastOperation) String() string            { return proto.CompactTextString(m) }
func (*LastOperation) ProtoMessage()               {}
func (*LastOperation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *LastOperation) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LastOperation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *LastOperation) GetAsyncPollIntervalSeconds() int32 {
	if m != nil {
		return m.AsyncPollIntervalSeconds
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func init() {
	proto.RegisterType((*Catalog)(nil), "pb.Catalog")
	proto.RegisterType((*Service)(nil), "pb.Service")
	proto.RegisterType((*Plan)(nil), "pb.Plan")
	proto.RegisterType((*Instance)(nil), "pb.Instance")
	proto.RegisterType((*Binding)(nil), "pb.Binding")
	proto.RegisterType((*ServiceBindingRequest)(nil), "pb.ServiceBindingRequest")
	proto.RegisterType((*ServiceBindingResponse)(nil), "pb.ServiceBindingResponse")
	proto.RegisterType((*ServiceInstanceRequest)(nil), "pb.ServiceInstanceRequest")
	proto.RegisterType((*ServiceInstanceResponse)(nil), "pb.ServiceInstanceResponse")
	proto.RegisterType((*Credential)(nil), "pb.Credential")
	proto.RegisterType((*LastOperation)(nil), "pb.LastOperation")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

func init() {
	proto.RegisterFile("github.com/getamis/service-broker/broker/pb/types.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0x86, 0xe4, 0x3f, 0x79, 0xbc, 0x4e, 0x36, 0x6c, 0xb7, 0x11, 0x76, 0xb1, 0x5d, 0x43, 0x05,
	0xba, 0x06, 0x8a, 0xda, 0x40, 0xf6, 0x90, 0xf6, 0xd0, 0xcb, 0x06, 0x45, 0x21, 0xb4, 0x40, 0x03,
	0x19, 0x39, 0x0b, 0x94, 0xc8, 0x68, 0x89, 0xa5, 0x29, 0x2e, 0x49, 0x05, 0x75, 0x1f, 0xa0, 0x6f,
	0xd0, 0x77, 0xea, 0x1b, 0xf4, 0xd4, 0x77, 0x29, 0x48, 0x51, 0x8a, 0x63, 0x17, 0x41, 0x0e, 0x3d,
	0x49, 0xf3, 0xcd, 0x70, 0xe6, 0x9b, 0x8f, 0xc3, 0x81, 0xcb, 0x8a, 0x99, 0x0f, 0x4d, 0xb1, 0x2a,
	0xeb, 0xed, 0xba, 0xa2, 0x06, 0x6f, 0x99, 0x5e, 0x6b, 0xaa, 0xee, 0x58, 0x49, 0xbf, 0x2d, 0x54,
	0xfd, 0x91, 0xaa, 0xb5, 0xff, 0xc8, 0x62, 0x6d, 0x76, 0x92, 0xea, 0x95, 0x54, 0xb5, 0xa9, 0x51,
	0x28, 0x8b, 0x97, 0xcf, 0xb4, 0x51, 0x4d, 0x69, 0x5a, 0x24, 0xb9, 0x80, 0xc9, 0x15, 0x36, 0x98,
	0xd7, 0x15, 0x7a, 0x0b, 0x91, 0x4f, 0xa2, 0xe3, 0x60, 0x31, 0x58, 0xce, 0x2e, 0x66, 0x2b, 0x59,
	0xac, 0x36, 0x2d, 0x96, 0xf5, 0xce, 0xe4, 0x9f, 0x10, 0x26, 0x1e, 0x45, 0x08, 0x86, 0x02, 0x6f,
	0x69, 0x1c, 0x2c, 0x82, 0xe5, 0x34, 0x73, 0xff, 0xe8, 0x04, 0x42, 0x46, 0xe2, 0xd0, 0x21, 0x21,
	0x23, 0x68, 0x01, 0x33, 0x42, 0x75, 0xa9, 0x98, 0x34, 0xac, 0x16, 0xf1, 0xc0, 0x39, 0xf6, 0x21,
	0xf4, 0x12, 0xa2, 0x82, 0x09, 0x82, 0x0b, 0x4e, 0xe3, 0xe1, 0x22, 0x58, 0x46, 0x59, 0x6f, 0xa3,
	0xb7, 0x70, 0x2a, 0x39, 0x16, 0x79, 0x23, 0x09, 0x36, 0xd4, 0x85, 0x8c, 0x5c, 0xc8, 0x89, 0x85,
	0x6f, 0x7a, 0xd4, 0x52, 0x31, 0xb8, 0xd2, 0xf1, 0x78, 0x31, 0xb0, 0x54, 0xec, 0xbf, 0x4d, 0xac,
	0xe8, 0xa7, 0x86, 0x29, 0xaa, 0xe3, 0x89, 0xc3, 0x7b, 0x1b, 0xbd, 0x83, 0x68, 0x4b, 0x0d, 0x26,
	0xd8, 0xe0, 0x38, 0x5a, 0x04, 0xcb, 0xd9, 0xc5, 0xf9, 0xaa, 0xaa, 0xeb, 0x8a, 0xd3, 0x56, 0x9b,
	0xa2, 0xb9, 0x5d, 0x6d, 0x9c, 0x56, 0x59, 0x1f, 0x88, 0xbe, 0x84, 0x91, 0x2d, 0xab, 0xe3, 0xa9,
	0x53, 0x28, 0xb2, 0x0a, 0x5d, 0x73, 0x2c, 0xb2, 0x16, 0x46, 0xef, 0xe1, 0x39, 0xc1, 0xfa, 0x43,
	0x51, 0x63, 0x45, 0xf2, 0x92, 0x33, 0x2a, 0x4c, 0x0c, 0x8f, 0x27, 0x3f, 0xed, 0x0f, 0x5c, 0xb9,
	0xf8, 0xe4, 0xcf, 0x00, 0x86, 0x36, 0xe7, 0xff, 0x24, 0xee, 0x7e, 0x9f, 0xc3, 0xa7, 0xf6, 0x89,
	0x60, 0x78, 0xab, 0x68, 0x27, 0xb5, 0xfb, 0x4f, 0xfe, 0x0e, 0x21, 0x4a, 0x85, 0x36, 0x58, 0x94,
	0x1d, 0x8f, 0xa0, 0xe7, 0xf1, 0x15, 0xcc, 0xef, 0x1b, 0x6f, 0x14, 0xf7, 0x14, 0x9f, 0xf5, 0xe0,
	0x8d, 0xe2, 0xe8, 0x0d, 0xcc, 0x98, 0x30, 0x54, 0x09, 0xcc, 0x73, 0x46, 0x3c, 0x59, 0xe8, 0xa0,
	0x94, 0xa0, 0xd7, 0x00, 0x7e, 0xcc, 0xac, 0x7f, 0xe8, 0xfc, 0x53, 0x8f, 0xa4, 0x04, 0x9d, 0xc3,
	0xc4, 0xcd, 0x02, 0x23, 0x8e, 0xd8, 0x34, 0x1b, 0x5b, 0x33, 0x25, 0xe8, 0x1b, 0x38, 0xab, 0x55,
	0x85, 0x05, 0xfb, 0x1d, 0xdb, 0x9e, 0xf3, 0xaa, 0x61, 0x24, 0x1e, 0xbb, 0x90, 0xe7, 0xfb, 0x8e,
	0x9f, 0x1a, 0xd6, 0x16, 0x91, 0xb8, 0xa4, 0x6d, 0xd4, 0xc4, 0x17, 0xb1, 0x88, 0x73, 0x7f, 0x07,
	0x27, 0x1c, 0x6b, 0x93, 0xd7, 0x92, 0x2a, 0x77, 0xc8, 0x4f, 0xc7, 0x99, 0xbd, 0xeb, 0x5f, 0xb0,
	0x36, 0xbf, 0x76, 0x8e, 0x6c, 0xce, 0xf7, 0x4d, 0x74, 0x09, 0x20, 0xb1, 0xc2, 0x5b, 0x6a, 0xa8,
	0xb2, 0x13, 0xf2, 0xa8, 0xd6, 0x7b, 0xa1, 0xc9, 0x5f, 0x01, 0x4c, 0xde, 0x33, 0x41, 0x98, 0xa8,
	0x8e, 0x84, 0x7d, 0x28, 0x49, 0x78, 0x28, 0xc9, 0x0b, 0x18, 0x63, 0x29, 0xef, 0xd5, 0x1c, 0x61,
	0x29, 0x53, 0x82, 0xbe, 0x86, 0xd3, 0xee, 0x54, 0xa7, 0x58, 0xab, 0xe6, 0xdc, 0xc3, 0xd7, 0xad,
	0x70, 0x6f, 0x60, 0x26, 0x15, 0xbb, 0xc3, 0x86, 0xe6, 0x1f, 0xe9, 0xce, 0xab, 0x0a, 0x1e, 0xfa,
	0x99, 0xee, 0xd0, 0x0a, 0x3e, 0xeb, 0xcb, 0xfb, 0xbb, 0xcf, 0x7b, 0x6d, 0xcf, 0x3a, 0x1e, 0xde,
	0x93, 0x92, 0xe4, 0x06, 0x5e, 0xf8, 0xdd, 0xe0, 0x1b, 0xca, 0xe8, 0xa7, 0x86, 0x6a, 0x73, 0xd0,
	0x47, 0x70, 0xd8, 0xc7, 0x6b, 0x80, 0xa2, 0x3d, 0xb0, 0xd7, 0xa6, 0x47, 0x52, 0x92, 0x6c, 0xe0,
	0x8b, 0xc3, 0xb4, 0x5a, 0xd6, 0x42, 0x53, 0xf4, 0x3d, 0xcc, 0x4a, 0x45, 0x09, 0x15, 0x86, 0x61,
	0xae, 0x5d, 0xe2, 0x47, 0x54, 0xdf, 0x8f, 0x4d, 0x2e, 0xfb, 0xa4, 0x5d, 0x03, 0x4f, 0x23, 0x9b,
	0xfc, 0x06, 0xe7, 0x47, 0x07, 0x3d, 0x9d, 0xa3, 0x77, 0x10, 0xfc, 0xc7, 0x3b, 0x38, 0x1e, 0xb1,
	0xf0, 0x69, 0x23, 0x96, 0xdc, 0x02, 0x5c, 0xf5, 0x1d, 0xa0, 0x57, 0x30, 0x95, 0x4d, 0xc1, 0x59,
	0x99, 0x33, 0xe9, 0x0b, 0x45, 0x2d, 0x90, 0x4a, 0xbb, 0xfb, 0x1a, 0x6d, 0x1f, 0xd6, 0x96, 0x7a,
	0x3d, 0x7b, 0xfb, 0xf0, 0xda, 0x07, 0x87, 0xd7, 0x9e, 0xfc, 0x11, 0xc0, 0xfc, 0x01, 0x11, 0xf4,
	0x39, 0x8c, 0xb4, 0xc1, 0xa6, 0xdb, 0x46, 0xad, 0x71, 0xb8, 0x7e, 0xc2, 0xe3, 0xf5, 0xf3, 0x03,
	0xbc, 0xc2, 0x7a, 0x27, 0xca, 0x5c, 0xd6, 0x9c, 0xe7, 0xee, 0xad, 0xdf, 0x61, 0x9e, 0x6b, 0x5a,
	0xd6, 0x82, 0x68, 0x57, 0x7a, 0x94, 0xc5, 0x2e, 0xe4, 0xba, 0xe6, 0x3c, 0xf5, 0x01, 0x9b, 0xd6,
	0x9f, 0x4c, 0x60, 0xf4, 0xe3, 0x56, 0x9a, 0x5d, 0x31, 0x76, 0x57, 0xf9, 0xee, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x41, 0xff, 0x67, 0x59, 0xfd, 0x06, 0x00, 0x00,
}
